In [1]:
%cd ../src

e:\00_CODE\03_Master_Thesis\rdf-literal-preprocessing\src


In [2]:
import fire
import sys
import tqdm
import pandas as pd
import numpy as np
import kgbench as kg
from collections import Counter
import matplotlib.pyplot as pl
import random as rd
from operator import itemgetter
import torch
import torch.nn.functional as F
from utils import RDF_NUMBER_TYPES, get_relevant_relations, add_triple, get_p_types, ALL_LITERALS
from kgbench.load import Data
from typing import List, Sequence, Tuple

from kgbench import load, tic, toc, d
import numpy as np
from sklearn.neighbors import LocalOutlierFactor
from utils import URI_PREFIX
import numpy as np
from sklearn.neighbors import LocalOutlierFactor
import datetime
from typing import List, Sequence, Tuple
from utils import URI_PREFIX
from preprocess.binning import delete_empty_bin_types

c:\Users\Noctris\.virtualenvs\rdf-literal-preprocessing-20b3_M0v\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
from dataload import dmg777k
data = dmg777k()
from utils.data_utils import data_to_kg, extract_ents, update_dataset_name, ensure_data_symmetry
data = ensure_data_symmetry(data)


from preprocess import delete_all_literals
data = delete_all_literals(data)


loaded data dmg777k (57.42s).
pruned (11.82s).


In [5]:

from embed import ComplEx
embedder = ComplEx(data)

train_entities, test_entities, train_target, test_taget = extract_ents(
    data)  
embeddings, train_embeddings, test_embeddings = embedder.fit_transform()



c:\Users\Noctris\.virtualenvs\rdf-literal-preprocessing-20b3_M0v\lib\site-packages\pystow\impl.py:92: DeprecationWarning: Use .module() instead
  warnings.warn("Use .module() instead", DeprecationWarning)
c:\Users\Noctris\.virtualenvs\rdf-literal-preprocessing-20b3_M0v\lib\site-packages\pystow\impl.py:92: DeprecationWarning: Use .module() instead
  warnings.warn("Use .module() instead", DeprecationWarning)
c:\Users\Noctris\.virtualenvs\rdf-literal-preprocessing-20b3_M0v\lib\site-packages\pystow\impl.py:92: DeprecationWarning: Use .module() instead
  warnings.warn("Use .module() instead", DeprecationWarning)
No random seed is specified. This may lead to non-reproducible results.
c:\Users\Noctris\.virtualenvs\rdf-literal-preprocessing-20b3_M0v\lib\site-packages\pykeen\triples\triples_factory.py:543: DeprecationWarning: Training instances are always shuffled.
  warnings.warn("Training instances are always shuffled.", DeprecationWarning)
Training epochs on cuda:0:   0%|          | 0/5 [00:

In [6]:
if embeddings.dtype == "complex64":
    train_embeddings_r = train_embeddings.real
    test_embeddings_r = test_embeddings.real

from evaluate import KNN
model = KNN()
model.fit(train_embeddings_r, train_target)

from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
predictions = model.predict(test_embeddings_r)
print(
    f"Predicted {len(test_entities)} entities with an accuracy of "
    + f"{accuracy_score(test_taget, predictions) * 100 :.4f}%"
    )
print(f'resulted in following f scores: micro {f1_score(test_taget, predictions, average="micro")} macro {f1_score(test_taget, predictions, average="macro")}')
print("Confusion Matrix :")
print(confusion_matrix(test_taget, predictions))

Predicted 2001 entities with an accuracy of 42.0790%
resulted in following f scores: micro 0.4207896051974013 macro 0.1649713634359776
Confusion Matrix :
[[  0  55   0  21   0]
 [  0 726   3 222   5]
 [  0 109   0  33   2]
 [  1 433   0 114   7]
 [  0 222   1  45   2]]


In [4]:
a = "hallo"
b = None
s = f"{a}{b}"

In [5]:
s

'halloNone'

In [3]:
import kgbench as kg
kg.load('amplus', True, True, prune_dist=None)

c:\Users\Noctris\.virtualenvs\rdf-literal-preprocessing-20b3_M0v\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


loaded data amplus (51.77s).


In [18]:
if embeddings.dtype == "complex64":
    train_embeddings_r = train_embeddings.real
    test_embeddings_r = test_embeddings.real

from thundersvm import SVC
model = SVC()

model.fit(train_embeddings_r, train_target)

from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
predictions = model.predict(test_embeddings_r)
print(
    f"Predicted {len(test_entities)} entities with an accuracy of "
    + f"{accuracy_score(test_taget, predictions) * 100 :.4f}%"
    )
print(f'resulted in following f scores: micro {f1_score(test_taget, predictions, average="micro")} macro {f1_score(test_taget, predictions, average="macro")}')
print("Confusion Matrix :")
print(confusion_matrix(test_taget, predictions))

FileNotFoundError: Please build the library first!

In [ ]:
import cudf
from cuml.svm import SVC
from cuml.datasets import make_classification

# Generate a synthetic dataset
X, y = make_classification(n_samples=10000, n_features=10, random_state=42)

# Convert the data to a GPU DataFrame
X = cudf.DataFrame(X)
y = cudf.Series(y)

# Create and train the SVM model
clf = SVC(kernel='linear')
clf.fit(X, y)

# Make predictions on new data
y_pred = clf.predict(X)