In [1]:
%cd ../src
import pickle
import pandas as pd
from utils import IMAGE_TYPES, RDF_DATE_TYPES, RDF_NUMBER_TYPES, POTENTIAL_TEXT_TYPES
import matplotlib.pyplot as plt
import torch
import numpy as np

e:\00_CODE\03_Master_Thesis\rdf-literal-preprocessing\src


c:\Users\Noctris\.virtualenvs\rdf-literal-preprocessing-20b3_M0v\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
def load_dataset(dataset):
    with open(f"../data/raw/{dataset}_final_torch_None.pickle", "rb") as f:
        data = pickle.load(f)
    
    print("# nodes")
    print(len(data.i2e))
    print("datatypes")
    print(data.datatypes())
    return data

In [3]:
data = load_dataset('amplus')

# nodes
1153221
datatypes
['iri', 'blank_node', 'none', 'http://kgbench.info/dt#base64Image', 'http://www.w3.org/2001/XMLSchema#date', 'http://www.w3.org/2001/XMLSchema#decimal', 'http://www.w3.org/2001/XMLSchema#positiveInteger']


In [4]:
from utils import get_relevant_relations, RDF_NUMBER_TYPES
relevant_relations = get_relevant_relations(data, RDF_NUMBER_TYPES)

In [5]:

from preprocess.binning import encode_number_sublist
sub_df = encode_number_sublist(data.triples[data.triples[:,1]== relevant_relations[0]], data.i2e)

In [12]:
num_bins = 10

In [14]:
sub_df[:,0].to(torch.int32)
torch.from_numpy(  # get numpy solutions back
                np.digitize(  # assign for each value in sub_df the corresponding bin
                    sub_df[:, 1], np.histogram(  # calculate n bins based on values in sub_df
                        sub_df[:, 1].to(torch.int32), num_bins)[1][:-1]
                )
            ).reshape(-1, 1)

tensor([[1],
        [1],
        [1],
        ...,
        [1],
        [1],
        [1]])

In [11]:
sub_df[:,0].to(torch.int32)
np.histogram(  # calculate n bins based on values in sub_df
                        sub_df[:, 1].to(torch.int32), 10)

(array([151621,     89,     14,      5,      2,      2,      0,      0,
             0,      1], dtype=int64),
 array([    0. ,  1510.6,  3021.2,  4531.8,  6042.4,  7553. ,  9063.6,
        10574.2, 12084.8, 13595.4, 15106. ]))

In [10]:
relevant_relations

[11, 15]

In [10]:
data.triples[torch.isin(data.triples[:,0], data.triples[:5,0])]

tensor([[ 123149,       9, 1083089],
        [ 123149,      10, 1151011],
        [ 123149,      11,   13270],
        [ 123149,      30,  778677],
        [ 123156,      30,  778681],
        [ 123156,      31,  872173]], dtype=torch.int32)

In [30]:
from preprocess import bin_numbers_lof_3, bin_numbers_percentage_15 
# data_aug = bin_numbers_lof_3(data)
data_aug = bin_numbers_percentage_15(data)

In [33]:
data_aug.i2r[39]

'http://multimodal-knowledge-graph-augmentation.com/predicat#binning11'

In [25]:
data_aug.e2i[('http://multimodal-knowledge-graph-augmentation.com/entity#binning1#relation15', 'http://multimodal-knowledge-graph-augmentation.com/datatype#bin')]

1153225

In [16]:
data_aug.i2r[37]

'http://multimodal-knowledge-graph-augmentation.com/predicat#outlier-11'

In [34]:
data_aug.triples[data_aug.triples[:,1]== 39][:,2].unique(return_counts=True)

(tensor([1153229, 1153230, 1153231, 1153232, 1153233, 1153234, 1153235, 1153236,
         1153237, 1153238, 1153239, 1153240, 1153241, 1153242, 1153243, 1153244,
         1153245, 1153246, 1153247, 1153248, 1153249, 1153250, 1153251, 1153252,
         1153253, 1153254, 1153255, 1153256, 1153257, 1153258, 1153259, 1153260,
         1153261, 1153262, 1153263, 1153264, 1153265, 1153266, 1153267, 1153268,
         1153269, 1153270, 1153271, 1153272, 1153273, 1153274, 1153275, 1153276,
         1153277, 1153278, 1153279, 1153280, 1153281, 1153282, 1153283, 1153284,
         1153285, 1153286, 1153287, 1153288, 1153289, 1153290, 1153291, 1153292,
         1153293, 1153294, 1153295, 1153296, 1153298, 1153300, 1153301, 1153302,
         1153303, 1153304, 1153305, 1153306, 1153307, 1153308, 1153309, 1153310,
         1153311, 1153312, 1153313, 1153314, 1153315, 1153316, 1153317, 1153318,
         1153319, 1153322, 1153324, 1153325, 1153326, 1153328, 1153330, 1153331,
         1153334, 1153335, 1

In [24]:
data_aug.i2e[19420]

('99', 'http://www.w3.org/2001/XMLSchema#decimal')

In [23]:
data_aug.triples[data_aug.triples[:,0]== 123314]

tensor([[ 123314,       9, 1070444],
        [ 123314,      10, 1151011],
        [ 123314,      11,   19420],
        [ 123314,      30,  778677],
        [ 123314,      37, 1153224]], dtype=torch.int32)

In [9]:
data_aug.i2e[-10:]

[('ô Manoach, stel ´t hert te vreên; Deeze Eng´le vlucht sterkt de Eng´le-reên, De wetgeving op Sinaï',
  'none'),
 ('‘Eén rechts, één averechts’ (‘knit and purl’)', 'none'),
 ('http://multimodal-knowledge-graph-augmentation.com/entity#binning1#relation11',
  'http://multimodal-knowledge-graph-augmentation.com/datatype#bin'),
 ('http://multimodal-knowledge-graph-augmentation.com/entity#binning2#relation11',
  'http://multimodal-knowledge-graph-augmentation.com/datatype#bin'),
 ('http://multimodal-knowledge-graph-augmentation.com/entity#binning3#relation11',
  'http://multimodal-knowledge-graph-augmentation.com/datatype#bin'),
 ('http://multimodal-knowledge-graph-augmentation.com/entitys#outlier-11',
  'http://multimodal-knowledge-graph-augmentation.com/outlier'),
 ('http://multimodal-knowledge-graph-augmentation.com/entity#binning1#relation15',
  'http://multimodal-knowledge-graph-augmentation.com/datatype#bin'),
 ('http://multimodal-knowledge-graph-augmentation.com/entity#binning2#rel

In [6]:
len(data_aug.triples)

2683405

In [8]:
len(data_aug.triples)

2683433

In [15]:
data_aug.triples[(data_aug.triples[:,0]==670633)&(data_aug.triples[:,1]==15)]

tensor([[670633,     15,  16240]], dtype=torch.int32)

In [9]:
data_aug.triples[(data_aug.triples[:,2]==1153237)]

tensor([[1153236,      34, 1153237],
        [1153238,      33, 1153237],
        [ 123821,      36, 1153237],
        [ 127216,      36, 1153237],
        [ 128683,      36, 1153237],
        [ 149083,      36, 1153237],
        [ 172239,      36, 1153237],
        [ 183097,      36, 1153237],
        [ 207964,      36, 1153237],
        [ 208382,      36, 1153237],
        [ 217638,      36, 1153237],
        [ 244136,      36, 1153237],
        [ 259362,      36, 1153237],
        [ 261619,      36, 1153237],
        [ 267153,      36, 1153237],
        [ 270919,      36, 1153237],
        [ 272760,      36, 1153237],
        [ 277309,      36, 1153237],
        [ 295323,      36, 1153237],
        [ 300775,      36, 1153237],
        [ 305186,      36, 1153237],
        [ 314590,      36, 1153237],
        [ 317800,      36, 1153237],
        [ 318826,      36, 1153237],
        [ 322370,      36, 1153237],
        [ 329642,      36, 1153237],
        [ 331956,      36, 1153237],
 

In [23]:
len(data_aug.i2e)

1153241

In [11]:
data.i2e[16240]

('47999', 'http://www.w3.org/2001/XMLSchema#positiveInteger')

In [12]:
data_aug.triples

tensor([[ 123149,       9, 1083089],
        [ 123149,      10, 1151011],
        [ 123149,      11,   13270],
        ...,
        [ 689268,      36, 1153231],
        [ 689313,      36, 1153231],
        [ 689381,      36, 1153231]], dtype=torch.int32)

In [8]:
data.num_entities

1153221

In [6]:
data_aug.num_entities

1153241