In [ ]:
%cd ../../src


In [2]:
from dataload import dmg777k
data = dmg777k()

loaded data dmg777k (56.13s).
pruned (9.463s).


In [ ]:
from preprocess import delete_number_literals, bin_numbers2, delete_literals,delete_all_literals

data = bin_numbers2(data,num_bins=10)
data = delete_number_literals(data)
#data = delete_all_literals(data)


In [4]:
from omegaconf import DictConfig, OmegaConf
import hydra
import dataload
import embed
import evaluate
from utils.data_utils import data_to_kg, extract_ents
import preprocess
from sklearn.metrics import accuracy_score, confusion_matrix
import logging
from embed import RDF2Vec, RGCN

embedder = RGCN(data)

train_entities, test_entities, train_target, test_taget = extract_ents(data)  # extract necessary fields from data
entities = train_entities + test_entities  # combine entities for embedding
kg = data_to_kg(data)  # transfrom data into kg


embeddings, _ = embedder.fit_transform(kg, entities)
train_embeddings = embeddings[: len(train_entities)]
test_embeddings = embeddings[len(train_entities):]




pykeen file does not exist. Writing pykeen file...


OSError: Cannot save file into a non-existent directory: 'data\preprocessed'

In [ ]:
embeddings

[array([ 0.5044803 ,  1.1620741 , -0.11921979, -0.4639484 ,  0.3423618 ,
        -0.21355438, -0.47642082,  1.4015348 ,  0.88173455, -0.24556136,
         1.052973  , -0.27050486,  0.88735735,  0.10028306, -0.6885142 ,
        -1.0545205 ,  0.15135314,  0.8553425 ,  1.1009247 , -0.22514783,
         0.331715  ,  0.574901  ,  0.03101657,  0.86409587,  0.20526996,
        -0.81356907,  0.0454748 , -0.11845043, -0.2752412 , -0.46257812,
        -0.4382108 , -0.19073515,  1.2517544 , -0.09361648, -0.7324751 ,
         0.8367837 ,  0.5104696 , -0.30833635,  0.6470767 ,  0.8075058 ,
        -0.7286257 , -0.2789566 ,  0.13492255,  0.42239138, -0.72772896,
         0.06042473, -0.01550555, -0.86397606, -0.00611893, -0.5335563 ,
        -0.47342604,  0.15673232, -0.8167499 , -0.977142  ,  1.1225973 ,
        -0.14973085,  0.43992814,  0.38372582,  0.28585315,  0.31180555,
        -0.02943084, -0.0666486 ,  0.33103046,  0.7395554 , -0.07832975,
         0.08212165,  0.9223923 ,  0.50832504, -1.2

In [ ]:
from evaluate import SVM
model = SVM()
model.fit(train_embeddings, train_target)
predictions = model.predict(test_embeddings)

print(f"Predicted {len(test_entities)} entities with an accuracy of "
        + f"{accuracy_score(test_taget, predictions) * 100 :.4f}%"
    )
print("Confusion Matrix :")
print(confusion_matrix(test_taget, predictions))

Predicted 2001 entities with an accuracy of 56.1219%
Confusion Matrix :
[[ 29   7   6   5  29]
 [ 89 571  20 119 157]
 [  4  14  97  15  14]
 [ 30  71  11 320 123]
 [ 48  78  11  27 106]]


In [ ]:
data.withheld

tensor([[174239,      1],
        [174112,      1],
        [173266,      1],
        ...,
        [173363,      4],
        [173584,      1],
        [173019,      1]])

In [1]:
from dataload import amplus
dataset = amplus()

c:\Users\Noctris\.virtualenvs\rdf-literal-preprocessing-20b3_M0v\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


loaded data amplus (50.63s).
pruned (30.25s).


In [6]:
dataset.i2e

[('', 'none'),
 ('                                                      sokkel in dep 3 kast 25',
  'none'),
 (' (1534-1603)', 'none'),
 (' (4 talen)', 'none'),
 (' (Duits)', 'none'),
 (' (Engels)', 'none'),
 (' (Frans)', 'none'),
 (' (Nederlands)', 'none'),
 (' (affiche)', 'none'),
 (' (verkeerspel)', 'none'),
 (' -1968)', 'none'),
 (' De Algemene Winkeliersvereniging aan mr. W.F. van Leeuwen bij zijn aftreden als burgemeester',
  'none'),
 (' Le canal du Heerengracht * bij de Spiegelstraat', 'none'),
 (' Natura Artis Magistra : 1838-1863 : Koninklijk Zoölogisch Genootschap',
  'none'),
 (' Transportnummer: 2009-0059                           in doos op grond',
  'none'),
 (' Transportnummer:2006-0316           doos 243', 'none'),
 (' We have no bananas', 'none'),
 (' brandewijnkom', 'none'),
 (' en scheepsmagazijn spuit 7 no. 27', 'none'),
 (' en scheepsmagazijn spuit R no. 35', 'none'),
 (' gegeven, tetjeroen zyn kluchtig leven. no. 27 (z.g. kinderprent)', 'none'),
 (" hierziet gij 

In [2]:
from utils import get_relevant_relations, RDF_NUMBER_TYPES
rr = get_relevant_relations(dataset, RDF_NUMBER_TYPES)

In [8]:
rr

[11, 15]

In [2]:
dataset.i2r[15]

'http://purl.org/collections/nl/am/exhibitionLref'

In [3]:
import numpy as np
import re
df_sub = dataset.triples[dataset.triples[:,1]==11]
for d in df_sub:
    np.double(dataset.i2e[d[2]][0])
    #print(dataset.i2e[d[2]][0])
    #m = re.search(r'[0-9]+\.?[0-9]*',dataset.i2e[d[2]][0])
    #if m != None:
    #    print(m.group())
    #    #pass
    #else:
    #    pass
        #print("WAS NOOOONE")
    #if()
    #print(np.double(re.search(r'[0-9]+\.?[0-9]*',dataset.i2e[d[2]][0]).group()))

In [ ]:
re.search()

In [14]:
df_sub[1,1]

tensor(11, dtype=torch.int32)

In [8]:
df_sub = dataset.triples[dataset.triples[:,1]==15]
for d in df_sub:
    print(np.double(dataset.i2e[d[2]][0]))

5596.0
4812.0
370.0
5855.0
5809.0
5546.0
5502.0
1109.0
5986.0
359.0
811.0
319.0
5275.0
47999.0
4694.0
4624.0
4591.0
5999.0
209.0
6252.0
5793.0
3921.0
6252.0
5716.0
6291.0
5171.0
359.0
5356.0
6291.0
5686.0
328.0
4363.0
1345.0
6285.0
4607.0
5911.0
446.0
4624.0
5596.0
5275.0
5502.0
5319.0
5921.0
5413.0
813.0
5936.0
4694.0
6041.0
4610.0
4624.0
5921.0
5171.0
5373.0
3028.0
813.0
328.0
6201.0
5205.0
5840.0
6178.0
5830.0
625.0
6049.0
5170.0
5756.0
370.0
331.0
5504.0
2249.0
5205.0
3376.0
260.0
5259.0
5205.0
5741.0
5319.0
47999.0
294.0
813.0
1109.0
870.0
5504.0
6291.0
6043.0
5630.0
4652.0
2037.0
5171.0
1874.0
5205.0
5502.0
813.0
237.0
5920.0
446.0
813.0
4603.0
4666.0
5171.0
6041.0
5171.0
446.0
5237.0
153.0
346.0
573.0
3826.0
5502.0
811.0
6201.0
359.0
4677.0
47999.0
4607.0
6072.0
5853.0
2616.0
5502.0
5287.0
4624.0
5707.0
4748.0
4610.0
2616.0
5960.0
5132.0
5504.0
811.0
5630.0
5651.0
5625.0
4696.0
4624.0
5156.0
5396.0
5756.0
5974.0
6080.0
1080.0
5275.0
5502.0
420.0
5435.0
5651.0
6041.0
4624.0
5171.